/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HelloImport } from './routes/hello'
import { Route as ContactIdImport } from './routes/$contactId'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const HelloRoute = HelloImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRoute,
} as any)

const ContactIdRoute = ContactIdImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$contactId': {
      id: '/$contactId'
      path: '/$contactId'
      fullPath: '/$contactId'
      preLoaderRoute: typeof ContactIdImport
      parentRoute: typeof rootRoute
    }
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$contactId': typeof ContactIdRoute
  '/hello': typeof HelloRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$contactId': typeof ContactIdRoute
  '/hello': typeof HelloRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$contactId': typeof ContactIdRoute
  '/hello': typeof HelloRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$contactId' | '/hello'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$contactId' | '/hello'
  id: '__root__' | '/' | '/$contactId' | '/hello'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactIdRoute: typeof ContactIdRoute
  HelloRoute: typeof HelloRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactIdRoute: ContactIdRoute,
  HelloRoute: HelloRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$contactId",
        "/hello"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$contactId": {
      "filePath": "$contactId.tsx"
    },
    "/hello": {
      "filePath": "hello.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
